# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
- group: LatestPackageVersions
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
              # Récupérer la valeur actuelle de la variable partagée
              currentVersion=$(LatestPackageVersions.7.x.x)
      
              # Lire la version à partir du fichier nuspec
              nuspecVersion=$(grep -oP '(?<=<version>)[^<]+' **/*.nuspec)
      
              echo "Current shared version: $currentVersion"
              echo "Version from nuspec: $nuspecVersion"
      
              if [ "$currentVersion" == "$nuspecVersion" ]; then
                echo "Error: Version needs to be updated!"
                exit 1
              else
                echo "Versions are different. Updating shared variable..."
                echo "##vso[task.setvariable variable=LatestPackageVersions.7.x.x;isOutput=true]$nuspecVersion"
              fi

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.nuspec'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'